name: ci

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        node: [18, 20, 21]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: "System dependencies"
        run: |
          sudo apt-get -y update
          sudo apt-get -y install libsnappy-dev python3 build-essential
      - run: pnpm install
      - run: |
          export PATH=bin:$PATH
          pnpm run lint && pnpm run build && pnpm run test
