name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-18.04
    timeout-minutes: 1
    strategy:
      matrix:
        node: [12,14,16]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: "System dependencies"
        run: |
          sudo apt-get -y update
          sudo apt-get -y install libsnappy-dev python3 build-essential
      - run: npm install

      - run: |
          export PATH=bin:$PATH
          npm test
