name: ci

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    strategy:
      matrix:
        node: [16,18,20]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "pnpm"
      - name: "System dependencies"
        run: |
          sudo apt-get -y update
          sudo apt-get -y install libsnappy-dev python3 build-essential
      - run: pnpm install
      - run: |
          export PATH=bin:$PATH
          pnpm run lint && pnpm run build && pnpm run test